version: "3"

services: 
  blockchain:
    image: node:14
    volumes: 
      - .:/blockchain
    working_dir: /blockchain
    entrypoint: npm run dev
    links: 
      - mongodb
    environment: 
      - MONGODB=mongodb
    ports: 
      - 3000:3000

  mongodb:
    image: mongo:latest
    logging:
      driver: none